---
# copied fro setup-redhat.yml, with minor changes

- name: install postgresql packages
  package: >-
    name={{ item }}
    state=installed
  with_items: "{{ postgresql_packages }}"
  register: postgresql_install_packages

- name: update pgdata bash_profile
  lineinfile: >-
    dest=/var/lib/postgresql/.bash_profile
    regexp="^PGDATA="
    line="PGDATA={{ postgresql_data_directory }}"
    backup=yes
  when: false

- name: template postgresql.service
  template: >-
    src=postgresql.service.j2
    dest=/etc/systemd/system/postgresql.service
    owner=root
    group=root
    mode=0644
  when: ansible_service_mgr == 'systemd'

- name: create postgresql data path
  file: >-
    path={{ postgresql_data_directory }}
    state=directory
    owner=postgres
    group=postgres
    mode=0700

- name: create postgresql backup path
  file: >-
    path={{ postgresql_backup_path }}
    state=directory
    owner=postgres
    group=postgres
    mode=0700
